version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: producer-farm-api-db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: farm-producer-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
